# Generated by Django 4.2.7 on 2024-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
